language: cpp
install:
  - wget https://dl.dropboxusercontent.com/u/15529534/cmake-2.8.12.tgz
  - tar -xf cmake-2.8.12.tgz
  - sudo cp -r cmake/* /usr
  - cmake --version
  - sudo pip install cpp-coveralls
script: cmake -DCOVERAGE=true . && make && make test
after_success:
  - sleep 5
  - coveralls --exclude cmake --exclude External
notifications:
  email: false
